<?php include("htdocs/includes/header.php"); ?>


<body class="init">
    <div class="pure-g"> 
       <?php include("htdocs/includes/leftsidebar.php"); ?>

        <div class="content pure-u-19-24">
            <aside id="categ_box">
                <div>
<p><strong>&Tau;&omicron;&mu;&epsilon;ί&sigmaf; &tau;&omicron;&upsilon; &Epsilon;.&Tau;.&Alpha;.&Alpha;. &ndash; &Tau;.&Sigma;.&Mu;.&Epsilon;.&Delta;.&Epsilon;.</strong></p>
<p>&Sigma;&tau;&omicron; &Epsilon;&nu;&iota;&alpha;ί&omicron; &Tau;&alpha;&mu;&epsilon;ί&omicron; (&Epsilon;.&Tau;.&Alpha;.&Alpha;.) &pi;&omicron;&upsilon; &sigma;&upsilon;&sigma;&tau;ή&theta;&eta;&kappa;&epsilon; &mu;&epsilon; &tau;&omicron; &Nu;.3655/08 &sigma;&upsilon;&sigma;&tau;ή&theta;&eta;&kappa;&alpha;&nu; &omicron;&iota; &Tau;&omicron;&mu;&epsilon;ί&sigmaf; :</p>
<p>&middot; <strong>&Tau;&omicron;&mu;έ&alpha;&sigmaf; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; (&Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;)</strong> &pi;&omicron;&upsilon; &pi;&epsilon;&rho;&iota;&lambda;&alpha;&mu;&beta;ά&nu;&epsilon;&iota; &tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Kappa;ύ&rho;&iota;&alpha;&sigmaf; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &sigma;&tau;&omicron;&nu; &omicron;&pi;&omicron;ί&omicron; &epsilon;&nu;&tau;ά&sigma;&sigma;&epsilon;&tau;&alpha;&iota; &kappa;&alpha;&iota; &eta; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta; &pi;&omicron;&upsilon; &alpha;&nu;&tau;&iota;&kappa;&alpha;&tau;έ&sigma;&tau;&eta;&sigma;&epsilon; &tau;&eta;&nu; &pi;&rho;ό&sigma;&theta;&epsilon;&tau;&eta; &sigma;ύ&nu;&tau;&alpha;&xi;&eta; &tau;&omicron;&upsilon; &Epsilon;.&Lambda;.&Pi;.&Pi;., &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&omicron; &Nu;.3518/2006.</p>
<p>&middot; <strong>&Tau;&omicron;&mu;έ&alpha;&sigmaf; &Epsilon;&pi;&iota;&kappa;&omicron;&upsilon;&rho;&iota;&kappa;ή&sigmaf; &Alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; (&Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;)</strong> &pi;&omicron;&upsilon; &pi;&epsilon;&rho;&iota;&lambda;&alpha;&mu;&beta;ά&nu;&epsilon;&iota; &tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Epsilon;&pi;&iota;&kappa;&omicron;&upsilon;&rho;&iota;&kappa;ή&sigmaf; &Alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; .</p>
<p>&middot; <strong>&Tau;&omicron;&mu;έ&alpha;&sigmaf; &Pi;&rho;ό&nu;&omicron;&iota;&alpha;&sigmaf; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; (&Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;)</strong> &pi;&omicron;&upsilon; &pi;&epsilon;&rho;&iota;&lambda;&alpha;&mu;&beta;ά&nu;&epsilon;&iota; &tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Epsilon;&phi;ά&pi;&alpha;&xi; &Pi;&alpha;&rho;&omicron;&chi;ώ&nu; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; .</p>
<p>&middot; <strong>&Tau;&omicron;&mu;έ&alpha;&sigmaf; &Epsilon;&iota;&delta;&iota;&kappa;ώ&nu; &Pi;&alpha;&rho;&omicron;&chi;ώ&nu; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; (&Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;)</strong> &pi;&omicron;&upsilon; &alpha;&nu;&tau;&iota;&sigma;&tau;&omicron;&iota;&chi;&epsilon;ί &sigma;&tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Epsilon;&iota;&delta;&iota;&kappa;ώ&nu; &Pi;&alpha;&rho;&omicron;&chi;ώ&nu; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;, &theta;&epsilon;&sigma;&mu;&omicron;&theta;&epsilon;&tau;ή&theta;&eta;&kappa;&epsilon; &mu;&epsilon; &tau;&omicron; &Nu;.3518/06 &kappa;&alpha;&iota; &delta;&epsilon;&nu; έ&chi;&epsilon;&iota; &gamma;ί&nu;&epsilon;&iota; έ&nu;&alpha;&rho;&xi;&eta; &tau;&eta;&sigmaf; &lambda;&epsilon;&iota;&tau;&omicron;&upsilon;&rho;&gamma;ί&alpha;&sigmaf; &tau;&omicron;&upsilon;.</p>
<p>&middot; <strong>&Tau;&omicron;&mu;έ&alpha;&sigmaf; &Upsilon;&gamma;&epsilon;ί&alpha;&sigmaf; &Tau;&epsilon;&chi;&nu;&iota;&kappa;ώ&nu; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; (&Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;)</strong> &pi;&omicron;&upsilon; &alpha;&nu;&tau;&iota;&sigma;&tau;&omicron;&iota;&chi;&epsilon;ί &sigma;&tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Upsilon;&gamma;&epsilon;ί&alpha;&sigmaf; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;.</p>
<p><strong>&Kappa;&lambda;ά&delta;&omicron;&iota; &Alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &tau;&omicron;&upsilon; &Epsilon;.&Tau;.&Alpha;.&Alpha;. &ndash; &Tau;.&Sigma;.&Mu;.&Epsilon;.&Delta;.&Epsilon;.</strong></p>
<p>&Omicron; &Tau;&omicron;&mu;έ&alpha;&sigmaf; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &delta;&iota;έ&pi;&epsilon;&tau;&alpha;&iota; &alpha;&pi;ό &tau;&iota;&sigmaf; &omicron;&iota;&kappa;&epsilon;ί&epsilon;&sigmaf; &kappa;&alpha;&tau;&alpha;&sigma;&tau;&alpha;&tau;&iota;&kappa;έ&sigmaf; &delta;&iota;&alpha;&tau;ά&xi;&epsilon;&iota;&sigmaf; &tau;&omicron;&upsilon; &Tau;&alpha;&mu;&epsilon;ί&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; ( &iota;&delta;&rho;ύ&theta;&eta;&kappa;&epsilon; &tau;&omicron; 1934 ) &mu;&epsilon; &tau;&omicron; &Alpha;.&Nu;. 2326/40 &laquo;&Pi;&epsilon;&rho;ί &Tau;&alpha;&mu;&epsilon;ί&omicron;&upsilon; &Sigma;&upsilon;&nu;&tau;ά&xi;&epsilon;&omega;&nu; &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;ώ&nu; &kappa;&alpha;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;ώ&nu; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu; &kappa;&alpha;&theta;ώ&sigmaf; &kappa;&alpha;&iota; &alpha;&pi;ό &sigma;ύ&nu;&omicron;&lambda;&omicron; &delta;&iota;&alpha;&tau;ά&xi;&epsilon;&omega;&nu; &pi;&omicron;&upsilon; &alpha;&phi;&omicron;&rho;&omicron;ύ&nu; &tau;&omicron;&upsilon;&sigmaf; &phi;&omicron;&rho;&epsilon;ί&sigmaf; &Kappa;&omicron;&iota;&nu;&omega;&nu;&iota;&kappa;ή&sigmaf; &Alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &raquo;.</p>
<p>&Eta; &pi;&alpha;&rho;&alpha;&pi;ά&nu;&omega; &nu;&omicron;&mu;&omicron;&theta;&epsilon;&sigma;ί&alpha; &tau;&rho;&omicron;&pi;&omicron;&pi;&omicron;&iota;ή&theta;&eta;&kappa;&epsilon; &mu;&epsilon; &tau;&omicron; &Nu;.915/79 &Phi;&Epsilon;&Kappa; 103/&Alpha;/8.5.79 &laquo;&Pi;&epsilon;&rho;ί &tau;&rho;&omicron;&pi;&omicron;&pi;&omicron;ί&eta;&sigma;&eta;&sigmaf; &kappa;&alpha;&iota; &sigma;&upsilon;&mu;&pi;&lambda;&eta;&rho;ώ&sigma;&epsilon;&omega;&sigmaf; &tau;&eta;&sigmaf; &nu;&omicron;&mu;&omicron;&theta;&epsilon;&sigma;ί&alpha;&sigmaf; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;&raquo; &kappa;&alpha;&iota; &mu;&epsilon; &tau;&omicron; &Nu;.3518/06 &Phi;&Epsilon;&Kappa; 272/21.12.06 &laquo;&Alpha;&nu;&alpha;&delta;&iota;ά&rho;&theta;&rho;&omega;&sigma;&eta; &tau;&omega;&nu; &kappa;&lambda;&alpha;&delta;&omega;&nu; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;&raquo; &mu;&epsilon; &iota;&sigma;&chi;ύ &alpha;&pi;ό 01/01/2007 &omega;&sigmaf; &epsilon;&xi;ή&sigmaf; :</p>
<p>&middot; <strong>&Kappa;&lambda;ά&delta;&omicron;&sigmaf; &kappa;ύ&rho;&iota;&alpha;&sigmaf; &sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf;</strong></p>
<p>&middot; <strong>&Kappa;&lambda;ά&delta;&omicron;&sigmaf; &epsilon;&pi;&iota;&kappa;&omicron;&upsilon;&rho;&iota;&kappa;ή&sigmaf; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf;</strong></p>
<p>&middot; <strong>&Kappa;&lambda;ά&delta;&omicron;&sigmaf; &upsilon;&gamma;&epsilon;ί&alpha;&sigmaf; &tau;&epsilon;&chi;&nu;&iota;&kappa;ώ&nu; (&Kappa;.&Upsilon;.&Tau;.)</strong></p>
<p>&middot; <strong>&Kappa;&lambda;ά&delta;&omicron;&sigmaf; &epsilon;&phi;ά&pi;&alpha;&xi; &pi;&alpha;&rho;&omicron;&chi;ώ&nu;</strong></p>
<p>&middot; <strong>&Kappa;&lambda;ά&delta;&omicron;&sigmaf; &epsilon;&iota;&delta;&iota;&kappa;ώ&nu; &pi;&alpha;&rho;&omicron;&chi;ώ&nu;</strong></p>
<p><strong>&Alpha;&sigma;&phi;&alpha;&lambda;&iota;&zeta;ό&mu;&epsilon;&nu;&alpha; &Pi;&rho;ό&sigma;&omega;&pi;&alpha; &sigma;&tau;&eta;&nu; &Kappa;ύ&rho;&iota;&alpha; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;</strong></p>
<p>1. &Tau;&alpha; &mu;έ&lambda;&eta; &tau;&omicron;&upsilon; &Tau;&epsilon;&chi;&nu;&iota;&kappa;&omicron;ύ &Epsilon;&pi;&iota;&mu;&epsilon;&lambda;&eta;&tau;&eta;&rho;ί&omicron;&upsilon; &Epsilon;&lambda;&lambda;ά&delta;&omicron;&sigmaf; (&Alpha;&rho;&chi;&iota;&tau;έ&kappa;&tau;&omicron;&nu;&epsilon;&sigmaf;, &Pi;&omicron;&lambda;&iota;&tau;&iota;&kappa;&omicron;ί &Mu;&eta;&chi;&alpha;&nu;&iota;&kappa;&omicron;ί &kappa;.&lambda;.&pi;.), &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&omicron;&nu; &Alpha;. &Nu;. 2326/40. &Eta; &epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή &sigma;&tau;&eta;&nu; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &sigma;&upsilon;&mu;&pi;ί&pi;&tau;&epsilon;&iota; &mu;&epsilon; &tau;&eta;&nu; &eta;&mu;&epsilon;&rho;&omicron;&mu;&eta;&nu;ί&alpha; &epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή&sigmaf; &sigma;&tau;&omicron; &Tau;&Epsilon;&Epsilon; &kappa;&alpha;&iota; &epsilon;ί&nu;&alpha;&iota; &upsilon;&pi;&omicron;&chi;&rho;&epsilon;&omega;&tau;&iota;&kappa;ή, &alpha;&nu;&epsilon;&xi;&alpha;&rho;&tau;ή&tau;&omega;&sigmaf; &tau;&eta;&sigmaf; &pi;&rho;&alpha;&gamma;&mu;&alpha;&tau;&iota;&kappa;ή&sigmaf; &alpha;&sigma;&kappa;ή&sigma;&epsilon;&omega;&sigmaf; &tau;&omicron;&upsilon; &epsilon;&pi;&alpha;&gamma;&gamma;έ&lambda;&mu;&alpha;&tau;&omicron;&sigmaf; &tau;&omicron;&upsilon; &mu;&eta;&chi;&alpha;&nu;&iota;&kappa;&omicron;ύ.</p>
<p>2. &Omicron;&iota; &Epsilon;&rho;&gamma;&omicron;&lambda;ή&pi;&tau;&epsilon;&sigmaf; &Delta;&eta;&mu;&omicron;&sigma;ί&omega;&nu; Έ&rho;&gamma;&omega;&nu;, &alpha;&pi;ό&phi;&omicron;&iota;&tau;&omicron;&iota; &tau;&omega;&nu; &Kappa;&Alpha;&Tau;&Epsilon;&Epsilon; &ndash; &Tau;&Epsilon;&Iota; έ&chi;&omicron;&nu;&tau;&epsilon;&sigmaf; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;&iota;&kappa;ό &Pi;&tau;&upsilon;&chi;ί&omicron; &Alpha;&tau;&omicron;&mu;&iota;&kappa;ή&sigmaf; &Epsilon;&pi;&iota;&chi;&epsilon;ί&rho;&eta;&sigma;&eta;&sigmaf; ή &nu;&alpha; &alpha;&nu;ή&kappa;&omicron;&upsilon;&nu; &sigma;&tau;&eta; &beta;&alpha;&sigma;&iota;&kappa;ή &sigma;&tau;&epsilon;&lambda;έ&chi;&omega;&sigma;&eta; &Epsilon;&tau;&alpha;&iota;&rho;ί&alpha;&sigmaf; &mu;&epsilon; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;&iota;&kappa;ό &Pi;&tau;&upsilon;&chi;ί&omicron; &kappa;&alpha;&iota; &gamma;&iota;&alpha; &tau;&omicron; &chi;&rho;ό&nu;&omicron; &pi;&omicron;&upsilon; &alpha;&upsilon;&tau;ό &epsilon;ί&nu;&alpha;&iota; &sigma;&epsilon; &iota;&sigma;&chi;ύ, &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&iota;&sigmaf; &upsilon;&pi;΄&alpha;&rho;&iota;&theta;&mu;. 1156/1997, 34/2002 &kappa;&alpha;&iota; 442/2002 &Alpha;&pi;&omicron;&phi;ά&sigma;&epsilon;&iota;&sigmaf; &tau;&omicron;&upsilon; &Delta;.&Sigma;. &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;.</p>
<p>&Delta;&iota;&epsilon;&upsilon;&kappa;&rho;ί&nu;&iota;&sigma;&eta; : &Eta; &epsilon;&gamma;&gamma;&rho;&alpha;&phi;ή &mu;έ&lambda;&omicron;&upsilon;&sigmaf; &omega;&sigmaf; &Epsilon;&Delta;&Epsilon; &iota;&sigma;&chi;ύ&epsilon;&iota; &alpha;&pi;ό &eta;&mu;&epsilon;&rho;&omicron;&mu;&eta;&nu;ί&alpha;&sigmaf; &upsilon;&pi;&omicron;&beta;&omicron;&lambda;ή&sigmaf; &tau;&eta;&sigmaf; &alpha;ί&tau;&eta;&sigma;&eta;&sigmaf; &kappa;&alpha;&iota; &gamma;&iota;&alpha; ό&sigma;&omicron; &delta;&iota;ά&sigma;&tau;&eta;&mu;&alpha; &tau;&omicron; &Epsilon;&rho;&gamma;&omicron;&lambda;&eta;&pi;&tau;&iota;&kappa;ό &Pi;&tau;&upsilon;&chi;ί&omicron; &epsilon;ί&nu;&alpha;&iota; &sigma;&epsilon; &iota;&sigma;&chi;ύ.</p>
<p>3. &Omicron;&iota; &epsilon;&lambda;&epsilon;ύ&theta;&epsilon;&rho;&alpha; &alpha;&pi;&alpha;&sigma;&chi;&omicron;&lambda;&omicron;ύ&mu;&epsilon;&nu;&omicron;&iota; &upsilon;&pi;&omicron;&mu;&eta;&chi;&alpha;&nu;&iota;&kappa;&omicron;ί &tau;&omega;&nu; &Sigma;&chi;&omicron;&lambda;ώ&nu; &tau;&omicron;&upsilon; &Nu;.&Delta;. 3971/59 &pi;&omicron;&upsilon; &tau;&epsilon;&lambda;&omicron;ύ&sigma;&alpha;&nu; &upsilon;&pi;ό &tau;&eta;&nu; &epsilon;&pi;&omicron;&pi;&tau;&epsilon;ί&alpha; &tau;&omicron;&upsilon; &Epsilon;.&Mu;.&Pi;. (&Nu;.915/79) &kappa;&alpha;&iota; &omicron;&iota; έ&mu;&mu;&iota;&sigma;&theta;&omicron;&iota; &upsilon;&pi;&omicron;&mu;&eta;&chi;&alpha;&nu;&iota;&kappa;&omicron;ί &tau;&omega;&nu; &Nu;.1027/80 &kappa;&alpha;&iota; &Nu;.1028/80.</p>
<p>4. &Omicron;&iota; &upsilon;&pi;ά&lambda;&lambda;&eta;&lambda;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &kappa;&alpha;&iota; &tau;&omicron;&upsilon; &Tau;&Epsilon;&Epsilon;, &sigma;ύ&mu;&phi;&omega;&nu;&alpha; &mu;&epsilon; &tau;&iota;&sigmaf; &delta;&iota;&alpha;&tau;ά&xi;&epsilon;&iota;&sigmaf; &tau;&omicron;&upsilon; &Nu;.1211/81.</p>
<p><strong>&Alpha;&sigma;&phi;&alpha;&lambda;&iota;&zeta;ό&mu;&epsilon;&nu;&alpha; &Pi;&rho;ό&sigma;&omega;&pi;&alpha; &sigma;&tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta;</strong></p>
<p>&Mu;&epsilon; &tau;&omicron; ά&rho;&theta;&rho;&omicron; 2 &tau;&omicron;&upsilon; &Nu;.3518/2006, &kappa;&alpha;&tau;&alpha;&rho;&gamma;&epsilon;ί&tau;&alpha;&iota; &omicron; &Epsilon;.&Lambda;.&Pi;.&Pi;. &alpha;&pi;ό 01/01/2007. &Eta; &pi;&rho;ό&sigma;&theta;&epsilon;&tau;&eta; &sigma;ύ&nu;&tau;&alpha;&xi;&eta; &tau;&omicron;&upsilon; &Lambda;&omicron;&gamma;&alpha;&rho;&iota;&alpha;&sigma;&mu;&omicron;ύ &alpha;&nu;&tau;&iota;&kappa;&alpha;&theta;ί&sigma;&tau;&alpha;&tau;&alpha;&iota; &alpha;&pi;ό &tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta;, &pi;&omicron;&upsilon; &beta;&alpha;&rho;ύ&nu;&epsilon;&iota; &tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Kappa;ύ&rho;&iota;&alpha;&sigmaf; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &kappa;&alpha;&iota; &kappa;&alpha;&tau;&alpha;&beta;ά&lambda;&lambda;&epsilon;&tau;&alpha;&iota; &alpha;&pi;ό &alpha;&upsilon;&tau;ό&nu;.</p>
<p>&Tau;&omicron; ά&rho;&theta;&rho;&omicron; 3 &tau;&omicron;&upsilon; &Nu;.3518/2006 &alpha;&nu;&alpha;&phi;έ&rho;&epsilon;&iota;, ό&tau;&iota; &sigma;&tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta; &upsilon;&pi;ά&gamma;&omicron;&nu;&tau;&alpha;&iota;:</p>
<p><strong>1. &Upsilon;&pi;&omicron;&chi;&rho;&epsilon;&omega;&tau;&iota;&kappa;ά &tau;&alpha; &kappa;ά&tau;&omega;&theta;&iota; &pi;&rho;ό&sigma;&omega;&pi;&alpha;:</strong></p>
<p>1. &Omicron;&iota; &mu;έ&chi;&rho;&iota; 31/12/1992 &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; (&pi;&alpha;&lambda;&alpha;&iota;&omicron;ί &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota;),</p>
<p>2. &Omicron;&iota; &alpha;&pi;ό 01/01/1993 (&nu;έ&omicron;&iota; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota;) &nbsp;&kappa;&alpha;&iota; &epsilon;&phi;&epsilon;&xi;ή&sigmaf; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;, &epsilon;&phi;ό&sigma;&omicron;&nu; έ&chi;&omicron;&upsilon;&nu; &sigma;&upsilon;&mu;&pi;&lambda;&eta;&rho;ώ&sigma;&epsilon;&iota; &delta;&epsilon;&kappa;&alpha;&epsilon;&tau;ή &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta; &sigma;&tau;&omicron; &kappa;&lambda;ά&delta;&omicron; &kappa;ύ&rho;&iota;&alpha;&sigmaf; &sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; &kappa;&alpha;&iota; &tau;&omicron; 35<sup>&omicron;</sup> έ&tau;&omicron;&sigmaf; &tau;&eta;&sigmaf; &eta;&lambda;&iota;&kappa;ί&alpha;&sigmaf; &tau;&omicron;&upsilon;&sigmaf;,</p>
<p>3. &omicron;&iota; &tau;&alpha;&kappa;&tau;&iota;&kappa;&omicron;ί &upsilon;&pi;ά&lambda;&lambda;&eta;&lambda;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;, &kappa;&alpha;&theta;ώ&sigmaf; &kappa;&alpha;&iota; &omicron;&iota; &upsilon;&pi;ά&lambda;&lambda;&eta;&lambda;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Epsilon;&Epsilon;</p>
<p><strong>2. &Pi;&rho;&omicron;&alpha;&iota;&rho;&epsilon;&tau;&iota;&kappa;ά ύ&sigma;&tau;&epsilon;&rho;&alpha; &alpha;&pi;ό &alpha;ί&tau;&eta;&sigma;ή &tau;&omicron;&upsilon;&sigmaf;:</strong></p>
<p>1. &omicron;&iota; &mu;έ&chi;&rho;&iota; 31/12/1992 (&pi;&alpha;&lambda;&alpha;&iota;&omicron;ί) &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;, &pi;&omicron;&upsilon; &kappa;&alpha;&tau;ά &tau;&eta;&nu; έ&nu;&alpha;&rho;&xi;&eta; &iota;&sigma;&chi;ύ&omicron;&sigmaf; &tau;&omicron;&upsilon; &pi;&alpha;&rho;ό&nu;&tau;&omicron;&sigmaf; &nu;ό&mu;&omicron;&upsilon; &alpha;&sigma;&phi;&alpha;&lambda;ί&zeta;&omicron;&nu;&tau;&alpha;&iota; ή &theta;&alpha; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&theta;&omicron;ύ&nu; &mu;&epsilon;&tau;&alpha;&gamma;&epsilon;&nu;έ&sigma;&tau;&epsilon;&rho;&alpha; &sigma;&epsilon; ά&lambda;&lambda;&omicron; &phi;&omicron;&rho;έ&alpha; &kappa;ύ&rho;&iota;&alpha;&sigmaf; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &tau;&eta;&sigmaf; &eta;&mu;&epsilon;&delta;&alpha;&pi;ή&sigmaf; ή &tau;&eta;&sigmaf; &alpha;&lambda;&lambda;&omicron;&delta;&alpha;&pi;ή&sigmaf; ή &sigma;&tau;&omicron; &Delta;&eta;&mu;ό&sigma;&iota;&omicron;,</p>
<p>2. &omicron;&iota; &alpha;&pi;ό 01/01/1993 (&nu;έ&omicron;&iota; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota;) &kappa;&alpha;&iota; &epsilon;&phi;&epsilon;&xi;ή&sigmaf; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&iota; &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon;, &epsilon;&phi;ό&sigma;&omicron;&nu; &delta;&epsilon;&nu; έ&chi;&omicron;&upsilon;&nu; &sigma;&upsilon;&mu;&pi;&lambda;&eta;&rho;ώ&sigma;&epsilon;&iota; &delta;&epsilon;&kappa;&alpha;&epsilon;&tau;ή &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta; &sigma;&tau;&omicron;&nu; &Kappa;&lambda;ά&delta;&omicron; &Kappa;ύ&rho;&iota;&alpha;&sigmaf; &Sigma;ύ&nu;&tau;&alpha;&xi;&eta;&sigmaf; ή &tau;&omicron; 35<sup>&omicron;</sup> έ&tau;&omicron;&sigmaf; &tau;&eta;&sigmaf; &eta;&lambda;&iota;&kappa;ί&alpha;&sigmaf; &tau;&omicron;&upsilon;&sigmaf;.</p>
<p>&Tau;&omicron; &Delta;.&Sigma;. &tau;&omicron;&upsilon; &Tau;&Sigma;&Mu;&Epsilon;&Delta;&Epsilon; &mu;&epsilon; &tau;&eta;&nu; &upsilon;&pi;&rsquo; &alpha;&rho;&iota;&theta;&mu;, 509/18-6-2008 &alpha;&pi;ό&phi;&alpha;&sigma;&eta;, &alpha;&pi;&omicron;&phi;ά&sigma;&iota;&sigma;&epsilon; &nbsp;&gamma;&iota;&alpha; &tau;&omicron;&upsilon;&sigmaf; &laquo;&nu;έ&omicron;&upsilon;&sigmaf;&raquo; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omicron;&upsilon;&sigmaf; &omega;&sigmaf; &epsilon;&xi;ή&sigmaf; :</p>
<p>1. &tau;&eta;&nu; &epsilon;&lambda;&epsilon;ύ&theta;&epsilon;&rho;&eta; &upsilon;&pi;&alpha;&gamma;&omega;&gamma;ή &sigma;&tau;&eta;&nu; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta; &tau;&eta;&sigmaf; &Epsilon;&iota;&delta;&iota;&kappa;ή&sigmaf; &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta;&sigmaf; &tau;&omega;&nu; &laquo;&nu;έ&omega;&nu;&raquo; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&mu;έ&nu;&omega;&nu; (&mu;&epsilon;&tau;ά &tau;&eta;&nu; 1.1.1993) &pi;&omicron;&upsilon; έ&chi;&omicron;&upsilon;&nu; &tau;&eta; &delta;&upsilon;&nu;&alpha;&tau;ό&tau;&eta;&tau;&alpha; &nu;&alpha; &upsilon;&pi;&alpha;&chi;&theta;&omicron;ύ&nu; &pi;&rho;&omicron;&alpha;&iota;&rho;&epsilon;&tau;&iota;&kappa;ά &chi;&omega;&rho;ί&sigmaf; &chi;&rho;&omicron;&nu;&iota;&kappa;ό &pi;&epsilon;&rho;&iota;&omicron;&rho;&iota;&sigma;&mu;ό &kappa;&alpha;&iota; &alpha;&nu;&alpha;&delta;&rho;&omicron;&mu;&iota;&kappa;ά &alpha;&pi;ό 01.01.2007.</p>
<p>2. &omicron;&iota; &kappa;&alpha;&tau;&alpha;&beta;&lambda;&eta;&theta;&epsilon;ί&sigma;&epsilon;&sigmaf; &epsilon;&iota;&sigma;&phi;&omicron;&rho;έ&sigmaf; &gamma;&iota;&alpha; &tau;&eta;&nu; &pi;&rho;&omicron;&alpha;&iota;&rho;&epsilon;&tau;&iota;&kappa;ή &upsilon;&pi;&alpha;&gamma;&omega;&gamma;ή &sigma;&tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta; &delta;&epsilon;&nu; &theta;&alpha; &epsilon;&pi;&iota;&sigma;&tau;&rho;έ&phi;&omicron;&nu;&tau;&alpha;&iota; &kappa;&alpha;&iota; &omicron; &epsilon;&nu; &lambda;ό&gamma;&omega; &chi;&rho;ό&nu;&omicron;&sigmaf; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &theta;&alpha; &epsilon;ί&nu;&alpha;&iota; &chi;&rho;ό&nu;&omicron;&sigmaf; &pi;&rho;&alpha;&gamma;&mu;&alpha;&tau;&iota;&kappa;ή&sigmaf; &alpha;&sigma;&phi;ά&lambda;&iota;&sigma;&eta;&sigmaf; &sigma;&tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta; &kappa;&alpha;&iota;</p>
<p>3. &tau;&eta;&nu; &epsilon;&lambda;&epsilon;ύ&theta;&epsilon;&rho;&eta; &alpha;&nu;ά&kappa;&lambda;&eta;&sigma;&eta; &tau;&omega;&nu; &alpha;&iota;&tau;ή&sigma;&epsilon;&omega;&nu; &pi;&rho;&omicron;&alpha;&iota;&rho;&epsilon;&tau;&iota;&kappa;ή&sigmaf; &upsilon;&pi;&alpha;&gamma;&omega;&gamma;ή&sigmaf; &sigma;&tau;&eta;&nu; &Epsilon;&iota;&delta;&iota;&kappa;ή &Pi;&rho;&omicron;&sigma;&alpha;ύ&xi;&eta;&sigma;&eta; &chi;&omega;&rho;ί&sigmaf; &chi;&rho;&omicron;&nu;&iota;&kappa;ό &pi;&epsilon;&rho;&iota;&omicron;&rho;&iota;&sigma;&mu;ό &kappa;&alpha;&iota; &alpha;&nu;&alpha;&delta;&rho;&omicron;&mu;&iota;&kappa;ά &alpha;&pi;ό 01/01/2007, &epsilon;&phi;ό&sigma;&omicron;&nu; &delta;&epsilon;&nu; έ&chi;&omicron;&upsilon;&nu; &kappa;&alpha;&tau;&alpha;&beta;&lambda;&eta;&theta;&epsilon;ί &omicron;&iota; &kappa;&alpha;&tau;ά &nu;ό&mu;&omicron; &alpha;&sigma;&phi;&alpha;&lambda;&iota;&sigma;&tau;&iota;&kappa;έ&sigmaf; &epsilon;&iota;&sigma;&phi;&omicron;&rho;έ&sigmaf; &gamma;&iota;&alpha; &tau;&omicron; &chi;&rho;ό&nu;&omicron; &pi;&omicron;&upsilon; &zeta;&eta;&tau;&epsilon;ί&tau;&alpha;&iota; &eta; &delta;&iota;&alpha;&gamma;&rho;&alpha;&phi;ή &raquo;.</p>
</div>
            </aside>
        </div>
    
    </div>
<?php include("htdocs/includes/footer.php"); ?>